import Head from "next/head";
const Meta = ({ title, keywords, description }) => {
  return (
    <Head>
      <title>Spishstories</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};
Meta.defaultProps = {
  title: "Spishstories",
  keywords: "nick spisak read stories darkestsideofthemoon",
  description: "Stories",
};
export default Meta;
